FinanceWatcher/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from app.views import dashboard, addresses, bills, groups, brands

urlpatterns = [
    path('', dashboard.dashboard, name="dashboard"),

    path("admin/", admin.site.urls),
    path("bills", bills.bills, name="bills"),
    path("bill/new", bills.CreateBillView.as_view(), name="create_bill"),
    path("bill/<int:bill_id>", bills.EditBillView.as_view(), name="edit_bill"),
    path("bill/<int:bill_id>/preview", bills.preview, name="preview_bill"),

    path("groups", groups.GroupsView.as_view(), name="groups"),
    path("group/<int:group_id>", groups.EditGroupView.as_view(), name="edit_group"),

    path("brands", brands.BrandListView.as_view(), name="brands"),
    path("brands/search", brands.search, name="search_brands"),
    path("brands/<int:brand_id>", brands.BrandDetailView.as_view(), name="brand_details"),
    path("brands/<int:brand_id>/addresses", brands.BrandAddressesListView.as_view(), name="brand_addresses"),
    path("brands/<int:brand_id>/assign-addresses", brands.assign_addresses, name="assign_addresses"),
    path("brands/<int:brand_id>/unassign-address", brands.unassign_address, name="unassign_address"),
    path("brands/<int:brand_id>/delete-address", brands.delete_address, name="delete_address"),
    path("brands/edit-brand-address/<int:brand_address_id>", brands.update_address, name="edit-brand-address-association"),

    path("addresses", addresses.get_all, name="addresses"),
    path("address", addresses.create, name="create_address"),
    path("addresses/search", addresses.search, name="search_addresses"),
    path("address/<int:address_id>", addresses.EditAddress.as_view(), name="edit_address"),

    # API Endpoints
    path("api/groups", groups.list_all, name="all_groups"),
    path("api/brands", brands.get_all, name="all_brands"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models/Brand.py
from __future__ import annotations

import os

from typing import Any, Dict

from django.db import models
from django.templatetags.static import static

from app.models.Address import Address
from app.models.BrandAddress import BrandAddress

from app.utils.images import save_as_thumbnail

class Brand(models.Model):
    name = models.CharField(max_length=200)
    addresses = models.ManyToManyField(Address, through=BrandAddress, blank=True)
    has_physical_stores = models.BooleanField(default=False)
    default_channel = models.CharField(max_length=100)
    icon = models.ImageField(db_column="icon", null=True, upload_to="brands")

    def save(self: Brand, file_was_uploaded: bool, *args, **kwargs):
        if self.icon and file_was_uploaded:
            # If there already exists a file with the given name, we need to delete it because otherwise
            # Django generates a new name and uses that one.
            full_path = os.path.join(self.icon.storage.location, "brands", self.icon.name)
            if os.path.isfile(full_path):
                os.remove(full_path)
            
            # Apparently, Django adds the prefix specified in the upload_to option even if it already
            # exists. So if it exists, we remove it to prevent accumulation
            if self.icon.name.startswith("brands"):
                self.icon.name = self.icon.name.lstrip("brands/")

            self.icon = save_as_thumbnail(self.icon, thumbnail_size=250)

        super().save(*args, **kwargs)

    def get_icon_url(self: Brand) -> str:
        """
        Returns the url of the uploaded image.
        If no image for this brand is present in the system,
        the url to the default brand icon is returned
        
        :param self: Description
        :type self: Brand
        :return: Description
        :rtype: str
        """
        if self.icon and hasattr(self.icon, 'url'):
            return self.icon.url
        
        return static(f"images/default_brand_icon.png")

    def to_json(self: Brand) -> Dict[str, Any]:
        return {
            "pk": self.pk,
            "name": self.name,
            "has_physical_stores": self.has_physical_stores,
            "default_channel": self.default_channel,
            "icon": self.get_icon_url()
        }

    class Meta:
        db_table = 'Brand'
    

app/forms/addresses.py
from django import forms

from app.models.Address import Address

class CreateAddressForm(forms.ModelForm):
    
    class Meta:
        model = Address
        exclude = []

app/views/addresses.py
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.views import View

from app.enums import Http
from app.forms.addresses import CreateAddressForm
from app.models.Address import Address
from app.models.BrandAddress import BrandAddress


def get_all(request: WSGIRequest) -> HttpResponse:
    addresses = Address.objects.order_by("-pk")
    create_address_form = CreateAddressForm()

    context = {
        "addresses": addresses,
        "create_address_form": create_address_form,
    }

    return render(request, "addresses/addresses.html", context)


def create(request: WSGIRequest) -> HttpResponse:
    form = CreateAddressForm(request.POST)

    if form.is_valid() is False:
        return JsonResponse({ "error": form.errors }, status=400)

    instance: Address = form.save()

    return JsonResponse(instance.to_dict(), status=Http.CREATED)

class EditAddress(View):
    def get(self, request: WSGIRequest, address_id: int) -> HttpResponse:
        try:
            address = Address.objects.get(id=address_id)
        except Address.DoesNotExist:
            return HttpResponse(status=404)
        
        data = {
            "id": address.id,
            "country": address.country.id,
            "region": address.region,
            "city": address.city,
            "street": address.street,
            "number": address.number,
            "additional_info": address.additional_info,
            "postal_code": address.postal_code,
        }

        return JsonResponse(data, status=200)

    def post(self, request: WSGIRequest, address_id: int) -> HttpResponse:
        try:
            address = Address.objects.select_related("country").get(id=address_id)
        except Address.DoesNotExist:
            return HttpResponse(status=404)
        
        form = CreateAddressForm(request.POST, instance=address)

        if form.is_valid() is False:
            return JsonResponse({ "error": form.errors }, status=400)

        instance: Address = form.save()

        return JsonResponse(instance.to_dict(), status=200)


    def delete(self, request: WSGIRequest, address_id: int) -> HttpResponse:
        try:
            address = Address.objects.get(id=address_id)
        except Address.DoesNotExist:
            return HttpResponse(status=404)
        
        address = Address.objects.get(id=address_id)
        address.delete()
        return HttpResponse(status=204)
    

def search(request: WSGIRequest) -> JsonResponse:
    exclude = request.GET.get("exclude", None)
    brand = request.GET.get("brand", None)
    country = request.GET.get("country", None)
    city = request.GET.get("city", None)
    region = request.GET.get("region", None)
    postal_code = request.GET.get("postal_code", None)

    addresses = Address.objects.all()

    if exclude is not None:
        brand_addresses_ids = BrandAddress.objects.filter(brand=exclude).only("pk").values_list("address_id", flat=True)
        addresses = addresses.exclude(pk__in=brand_addresses_ids)

    if brand is not None:
        addresses = addresses.filter(brand=brand)

    if country is not None:
        addresses = addresses.filter(country=country)

    if city is not None:
        addresses = addresses.filter(city=city)

    if region is not None:
        addresses = addresses.filter(region=region)
    if postal_code is not None:
        addresses = addresses.filter(postal_code=postal_code)

    return JsonResponse(list(addresses.values()), safe=False)

app/views/brands.py
from __future__ import annotations

import os

from datetime import date, timedelta

from django.core.handlers.wsgi import WSGIRequest
from django.forms.models import model_to_dict
from django.http import (
    JsonResponse,
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseNotFound
)
from django.shortcuts import render
from django.views import View

from app.enums import Http
from app.forms.brands import (
    AssignAddressesForm,
    CreateBrandForm,
    EditAddressAssociationForm,
    EditBrandForm
)

from app.models.Address import Address
from app.models.Brand import Brand
from app.models.BrandAddress import BrandAddress
from app.models.Country import Country

from app.shortcuts import get_object_or_404

from app.utils.request import (
    get_date_from_request,
    get_date_from_request_or_bad_request
)

def get_all(self: WSGIRequest) -> JsonResponse:
    brands = Brand.objects.order_by("name")
    return JsonResponse({"brands": list(brands)})


class BrandListView(View):
    def get(self: BrandListView, request: WSGIRequest):
        """
        Renders a list with all brands known in the system
        
        :param self: Description
        :type self: BrandListView
        :param request: Description
        :type request: WSGIRequest
        """

        brands = Brand.objects.order_by("name")

        create_brand_form = CreateBrandForm()

        context = {
            "brands": brands,
            "create_brand_form": create_brand_form
        }

        return render(request, "brands/brands.html", context)

    def post(self: BrandListView, request: WSGIRequest):
        """
        Creates a new brand
        
        :param self: Description
        :type self: BrandListView
        :param request: Description
        :type request: WSGIRequest
        """
        create_brand_form = CreateBrandForm(request.POST, request.FILES)

        if create_brand_form.is_valid() is False:
            errors = {
                "form": create_brand_form.errors
            }
            return JsonResponse(errors, status=Http.BAD_REQUEST)
        
        new_brand: Brand = create_brand_form.save(commit=False)
        new_brand.save(file_was_uploaded="icon" in request.FILES)

        brand_dict = model_to_dict(new_brand, exclude=["icon"])
        brand_dict["icon"] = new_brand.get_icon_url()
        return JsonResponse(brand_dict)
    
class BrandDetailView(View):
    def get(self: BrandDetailView, request: WSGIRequest, brand_id: int):
        try:
            brand = Brand.objects.get(id=brand_id)
        except Brand.DoesNotExist:
            return HttpResponseNotFound(f"Es existiert keine Marke mit der ID {brand_id}")
        
        return JsonResponse(brand.to_json())

    def post(self: BrandDetailView, request: WSGIRequest, brand_id: int):
        try:
            brand = Brand.objects.get(id=brand_id)
        except Brand.DoesNotExist:
            return HttpResponseNotFound(f"Es existert keine Marke mit der ID {brand_id}")

        edit_brand_form = EditBrandForm(request.POST, request.FILES, instance=brand)
        if edit_brand_form.is_valid() is False:
            errors = {
                "form": edit_brand_form.errors
            }
            return JsonResponse(errors, status=Http.BAD_REQUEST)
        
        edited_brand: Brand = edit_brand_form.save(commit=False)
        edited_brand.save(file_was_uploaded="icon" in request.FILES)

        return JsonResponse(edited_brand.to_json())

    def delete(self: BrandDetailView, request: WSGIRequest, brand_id: int) -> HttpResponse:
        try:
            brand = Brand.objects.get(id=brand_id)
        except Brand.DoesNotExist:
            return HttpResponseNotFound(f"Es existiert keine Marke mit der ID {brand_id}")

        if os.path.exists(brand.icon.path):
            os.remove(brand.icon.path)

        brand.delete()

        return HttpResponse()
    
class BrandAddressesListView(View):
    def get(self: BrandAddressesListView, request: WSGIRequest, brand_id: int) -> HttpResponse:
        try:
            brand = Brand.objects.get(pk=brand_id)
        except Brand.DoesNotExist:
            return HttpResponseNotFound(f"Es gibt keine Marke mit der ID f{brand_id}")
        
        countries = Country.objects.all()
        brand_address_associations = BrandAddress.objects.filter(brand=brand).select_related("address")

        context = {
            "brand": brand,
            "brand_address_associations": brand_address_associations,
            "assign_addresses_form": AssignAddressesForm(addresses=Address.objects.none()),
            "edit_address_association_form": EditAddressAssociationForm(),
            "countries": countries
        }

        return render(request, "brands/addresses.html", context)
    

def assign_addresses(request: WSGIRequest, brand_id: int) -> HttpResponse:
    brand: Brand = get_object_or_404(Brand, pk=brand_id, json=True)

    address_ids = request.POST.getlist("addresses")
    start_date = get_date_from_request_or_bad_request(request, "start_date")
    end_date = get_date_from_request(request, "end_date")

    if start_date > end_date:
        return HttpResponseBadRequest("The start date cannot be after the end date")

    # Since the addresses can be in use, make sure that the end date is properly set
    BrandAddress.objects.filter(address__in=address_ids).update(end_date=start_date - timedelta(days = 1))

    # Create new mappings between addresses and the brand starting from today
    new_address_associations = (
        BrandAddress(
            brand=brand,
            address_id=address_id,
            start_date=start_date,
            end_date=end_date
        )
        for address_id
        in address_ids
    )
    created_db_objects = BrandAddress.objects.bulk_create(new_address_associations)

    addresses = BrandAddress.objects.filter(
        pk__in=[address.pk for address in created_db_objects]
    ).select_related("address")
    
    response = {
        "brand": brand.to_json(),
        "addresses": [
            address.to_json(include_brand=False)
            for address
            in addresses
        ]
    }

    return JsonResponse(response, safe=False, status=Http.CREATED)


def unassign_address(request: WSGIRequest, brand_id: int) -> HttpResponse:
    """
    Unassigns an address from a brand. Only works if the address is currently assigned to the brand
    (no end date is specified)
    
    :param request: Description
    :type request: WSGIRequest
    :param brand_id: Description
    :type brand_id: int
    :return: Description
    :rtype: HttpResponse
    """
    brand: Brand = get_object_or_404(Brand, pk=brand_id, json=True)

    brand_address_id = request.GET.get("address", None)

    if brand_address_id is None:
        return HttpResponseBadRequest("ID der Addresse benötigt")
    
    brand_address: BrandAddress = get_object_or_404(BrandAddress, pk=brand_address_id, json=True)
    if brand_address.brand_id != brand.pk:
        return HttpResponseBadRequest(f"Addresse gehört nicht zu {brand.name}")

    brand_address.end_date = date.today() - timedelta(days=1)
    brand_address.save()

    return JsonResponse(brand_address.to_json())

def delete_address(request: WSGIRequest, brand_id: int) -> HttpResponse:
    """
    Deletes the association between the brand and the address
    This can be used if an address was mistakenly assigned to a brand.
    
    :param request: Description
    :type request: WSGIRequest
    :param brand_id: Description
    :type brand_id: int
    :return: Description
    :rtype: HttpResponse
    """
    brand: Brand = get_object_or_404(Brand, pk=brand_id, json=True)

    brand_address_id = request.GET.get("address", None)

    if brand_address_id is None:
        return HttpResponseBadRequest("ID der Addresse benötigt")
    
    brand_address: BrandAddress = get_object_or_404(BrandAddress, pk=brand_address_id, json=True)
    if brand_address.brand_id != brand.pk:
        return HttpResponseBadRequest(f"Addresse gehört nicht zu {brand.name}")

    brand_address.delete()

    return HttpResponse()

def update_address(request: WSGIRequest, brand_address_id) -> HttpResponse:
    brand_address: BrandAddress = get_object_or_404(
        BrandAddress,
        pk=brand_address_id,
        error_message="Address association does not exist",
        json=True
    )

    edit_address_association_form = EditAddressAssociationForm(request.POST)

    if edit_address_association_form.is_valid() == False:
        return JsonResponse(edit_address_association_form.errors, status=Http.BAD_REQUEST)
    
    start_date = edit_address_association_form.cleaned_data.get("start_date")
    end_date = edit_address_association_form.cleaned_data.get("end_date")
    brand_address.start_date = start_date
    brand_address.end_date = end_date
    brand_address.save()

    json_response = brand_address.to_json(include_brand=False, include_id=False)    

    return JsonResponse(json_response)

def search(request: WSGIRequest) -> JsonResponse:
    query = request.GET.get("query", None)

    if query is None:
        return HttpResponseBadRequest("Query parameter missing")
    
    brands = Brand.objects.filter(name__icontains=query).order_by("name").only("name", "icon")
    return JsonResponse([brand.to_json() for brand in brands], safe=False)

app/templates/brands/addresses.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% load crispy_forms_tags %}

{% block js %}
    <script src="{% static 'js/brands.js' %}"></script>
{% endblock %}

{% block content %}
    <h1>{% trans 'Addresses' %}</h1>

    <button class="btn btn-primary mb-3" onclick="onAssignAddressesClicked(event)">
        <i class="fa fa-plus mr-2"></i>
        {% trans 'Add address' %}
    </button>
    <table id="brand-addresses-table" class="table table-bordered">
        <thead>
            <tr>
                <th>{% trans 'Street' %}</th>
                <th>{% trans 'City' %}</th>
                <th>{% trans 'Postal Code' %}</th>
                <th>{% trans 'Region' %}</th>
                <th>{% trans 'Country' %}</th>
                <th>{% trans 'From' %}</th>
                <th>{% trans 'To' %}</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% comment %}
                The dummy table row makes sure that there is always at least one table row with the proper cells
                so it can be copied to create new rows.
            {% endcomment %}
            <tr class="dummy">
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    <button class="btn btn-close" title="{% trans 'Edit address' %}" onclick="onEditAssociationClicked(event)">
                        <i class="fa-solid fa-lg fa-edit no-events"></i>
                    </button>
                    <button class="btn btn-close" title="{% trans 'Unassign address' %}" onclick="onUnassignAddressClicked(event)">
                        <i class="fa fa-lg fa-xmark no-events"></i>
                    </button>
                    <button class="btn btn-close" title="{% trans 'Delete address' %}" onclick="onDeleteAddressClicked(event)">
                        <i class="fa fa-lg fa-trash no-events"></i>
                    </button>
                </td>
            </td>
            {% for association in brand_address_associations %}
                <tr id="association-table-row-{{ association.pk }}">
                    <td>{{ association.address.street }} {{ association.address.number }}</td>
                    <td>{{ association.address.city }}</td>
                    <td>{{ association.address.postal_code }}</td>
                    <td>{{ association.address.region }}</td>
                    <td>{{ association.address.country }}</td>
                    <td>{{ association.start_date|date:"d.m.Y" }}</td>
                    <td>{{ association.end_date|default_if_none:"-"|date:"d.m.Y" }}</td>
                    <td>
                        <button
                            class="btn btn-close"
                            title="{% trans 'Edit address' %}"
                            onclick="onEditAssociationClicked(event)"
                            data-id="{{ association.pk }}"
                            data-from="{{ association.start_date|date:"Y-m-d" }}"
                            data-to="{{ association.end_date |date:"Y-m-d"}}"
                        >
                            <i class="fa-solid fa-lg fa-edit no-events"></i>
                        </button>
                        <button 
                            class="btn btn-close"
                            title="{% trans 'Delete address' %}"
                            onclick="onDeleteAddressClicked(event)"
                            data-id="{{ association.pk }}"
                        >
                            <i class="fa fa-lg fa-trash no-events"></i>
                        </button>
                        {% if association.is_currently_assigned is False %}
                            <button 
                                class="btn btn-close"
                                title="{% trans 'Unassign address' %}"
                                onclick="onUnassignAddressClicked(event)"
                                data-id="{{ association.pk }}"
                            >
                                <i class="fa fa-lg fa-xmark no-events"></i>
                            </button>
                        {% endif %}
                    </td>
                </tr>
            {% empty %}
                <tr class="no-data">
                    <td colspan="8">{% trans 'This brand does not have addresses assigned to it' %}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <dialog id="edit-association-dialog">
        <div class="content">
            <header>
                <h1>{% trans 'Edit address association' %}</h1>
            </header>
            <div class="body">
                <form id="edit-address-association-form" onsubmit="onEditAddressAssociationFormSubmitted(event)">
                    <input type="hidden" name="id">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                            {{ edit_address_association_form.start_date|as_crispy_field }}
                        </div>
                        <div class="col-md-6">
                            {{ edit_address_association_form.end_date|as_crispy_field }}
                        </div>
                    </div>
                </form>
            </div>
            <footer>
                <button class="btn btn-primary" type="submit" form="edit-address-association-form">
                    <i class="fa fa-save mr-2"></i>
                    {% trans 'Save' %}
                </button>
                <button class="btn btn-danger" type="cancel">
                    <i class="fa fa-xmark mr-2"></i>
                    {% trans 'Cancel' %}
                </button>
            </footer>
        </div>
    </dialog>

    <dialog id="assign-brand-address-dialog">
        <div class="content">
            <header>
                <h1>{% trans 'Add Addresses' %}</h1>
            </header>
            <div class="body">
                <form id="address-filter-form" onsubmit="onAddressFormSubmitted(event)">
                    <input name="id" type="hidden">
                    {% csrf_token %}
                    <div class="form-row mb-2">
                        <div class="col-md-6">
                            <select 
                                name="country"
                                class="custom-select"
                                onChange="onAssignAddressInputChanged(event)"
                            >
                                {% for country in countries %}
                                    <option value="{{ country.pk }}">{{ country.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-6">
                            <input 
                                class="form-control"
                                type="text"
                                name="city"
                                placeholder="City"
                                onkeyup="onAssignAddressInputChanged(event)"
                            >
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-md-6">
                            <input
                                class="form-control"
                                type="text"
                                name="region"
                                placeholder="Region"
                                onkeyup="onAssignAddressInputChanged(event)"
                            >
                        </div>
                        <div class="col-md-6">
                            <input
                                class="form-control"
                                type="text"
                                name="postal_code"
                                placeholder="Postleitzahl"
                                onkeyup="onAssignAddressInputChanged(event)"
                            >
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md">
                            <button 
                                class="btn btn-primary"
                                onclick="onUpdateAddressesClicked(event)"
                            >
                                <i class="fa fa-undo mr-2"></i>
                                {% trans 'Update' %}
                            </button>
                        </div>
                    </div>
                </form>
                <form 
                    id="assign-addresses-form"
                    class="mt-3"
                    onsubmit="onAssignAddressesFormSubmitted(event)"
                >
                    {% csrf_token %}
                    <div class="row mb-2">
                        <div class="col-md">
                            {{ assign_addresses_form.addresses|as_crispy_field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            {{ assign_addresses_form.start_date|as_crispy_field }}
                        </div>
                        <div class="col-md-6">
                            {{ assign_addresses_form.end_date|as_crispy_field }}
                        </div>
                    </div>
                </form>
            </div>
            <footer>
                <button class="btn btn-primary" type="submit" form="assign-addresses-form">
                    <i class="fa fa-save mr-2"></i>
                    {% trans 'Assign addresses' %}
                </button>
                <button class="btn btn-danger" type="cancel">
                    <i class="fa fa-xmark mr-2"></i>
                    {% trans 'Cancel' %}
                </button>
            </footer>
        </div>
    </dialog>

    <script>
        const BRAND_ID = "{{ brand.pk }}";
        const SEARCH_ADDRESSES_URL = "{% url 'search_addresses' %}";
        const ASSIGN_ADDRESSES_URL = "{% url 'assign_addresses' 0 %}";
        const UNASSIGN_ADDRESS_URL = "{% url 'unassign_address' 0 %}";
        const DELETE_ADDRESS_URL = "{% url 'delete_address' 0 %}";
        const EDIT_ADDRESS_ASSOCIATION_URL = "{% url 'edit-brand-address-association' 0 %}";
    </script>
{% endblock %}

app/templates/brands/create.html
{% load crispy_forms_tags %}

{% load static %}
{% load i18n %}

<header>
  <h1>{% trans 'Add brand' %}</h1>
</header>

<main>
  <form
    id="create-brand-form"
    class="p-4"
    onsubmit="onBrandFormSubmitted(event)"
    enctype="multipart/form-data"
  >
    <div class="form-row">
      {% csrf_token %} 
      <input type="hidden" name="id">
    </div>
    <div class="form-row">
      <div class="col-md">{{ create_form.name|as_crispy_field }}</div>
    </div>
    <div class="form-row">
      <div class="col-md">{{ create_form.has_physical_stores|as_crispy_field }}</div>
      <div class="col-md">{{ create_form.default_channel|as_crispy_field }}</div>
    </div>
    <div class="form-row">
      <div class="col-md-6">
        <div class="form-group">
          <label class="requiredField">{% trans 'Image' %}</label>
          <div>
            <input
              id="id_icon"
              class="clearablefileinput form-control-file"
              style="display: none"
              type="file"
              name="icon"
              accept="image/*"
              onchange="onBrandImageChanged(event)"              
            />
            <label for="id_icon">
              <h3>{% trans 'Choose image' %}</h3>
              <img src="{% static 'images/upload.png' %}" alt="Bild auswählen" />
            </label>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label>{% trans 'Preview' %}</label>
          <img id="brand-image-preview" class="image-preview" src="{% static 'images/default_brand_icon.png' %}" style="width: 250px; height: 250px" />
        </div>
      </div>
    </div>
  </form>
</main>
<footer>
  <button class="btn btn-primary" form="create-brand-form" type="submit">
    <i class="fa fa-save mr-2"></i>
    {% trans 'Save' %}
  </button>
  <button class="btn btn-danger" type="cancel" onclick="onBrandAbortClicked(event)">
    <i class="fa fa-xmark mr-2"></i>
    {% trans 'Cancel' %}
  </button>
</footer>